### Get all countries
GET http://localhost:8080/countries

###

### Get country by code
GET http://localhost:8080/countries/IN

###

### Add country
POST http://localhost:8080/countries
Content-Type: application/json

{
  "code": "JP",
  "name": "Japan"
}

###

### Update country
PUT http://localhost:8080/countries/JP
Content-Type: application/json

{
  "code": "JP",
  "name": "Japan Updated"
}

###

### Delete country
DELETE http://localhost:8080/countries/JP